### ISSUE TITLE
Catch SSL errors in a more transparent manner

### ISSUE THREAD

**Issue by jpmschuler** [pablopaul/codeceptjs-slack-reporter#2]
Scenario:
This great plugin had a hiccup in our CI after the CI runners where put behind a WAF, where each and every domain/URL needs whitelisting. The WAF will return a self-signed error page in the domain is not whitelisted. Slack wasn't whitelisted for that machine.

What happened:
One test failed and the plugin tried to reach `https://slack.com/api` which resulted in multiple
```
[WARN]  web-api:WebClient:0 http request failed self signed certificate in certificate chain
Error: A request error occurred: self signed certificate in certificate chain
    at Object.requestErrorWithOriginal (/path/to/node_modules/@slack/web-api/dist/errors.js:28:33)
    at /path/to/node_modules/@slack/web-api/dist/WebClient.js:280:36
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (/path/to/node_modules/p-queue/dist/index.js:163:29) {
  code: 'slack_webapi_request_error',
```

Annoyance:
The real problem with this unhandled problem was not that an exception occurred, however it retried to make the call resulting in 23min of single test case execution.

I know that this might be considered an edge case,  and `@slack/bolt` doesn't have that much configuration options (I can read the API, but Javascript, isn't my expertise) but probably a simple pokemon exception handling in this plugin would already suffice?

**Comment by pablopaul** [comment]
@jpmschuler thanks for reporting your specific issue.

I remember having a similar case and could imagine that the way you described may fix it. 

If you want to get it released I need a well tested PR, unfortuantely I dont have time to dive into this myself right now.

**Comment by jpmschuler** [comment]
As said, I have to less expertise in JS to supply stable code. 
That said I dug deeper into docs and libs and pokemon catching doesn't seem possible on this level. Concerning the missing options and sophisticated wrapping it seems `@slack/web-api` would need the fix (or need to expose timeout/retry options or update the docs to show that they can be overridden).
https://github.com/slackapi/node-slack-sdk/issues/1440

**Comment by jpmschuler** [comment]
As a followUp for context and reference: 

The exception won't and shouldn't be handled, the retries are configureable:

1. there is a default option in slack web-api  `retryConfig = tenRetriesInAboutThirtyMinutes,` which is detailed in https://slack.dev/node-slack-sdk/web-api#automatic-retries and found in https://github.com/slackapi/node-slack-sdk/blob/f134cf220c5cee462dc3fc1558d65dc5f2c9cbfc/packages/web-api/src/WebClient.ts#L157
2. That option is handed over from the bolt lib via `clientOptions`:   clientOptions?: Pick<WebClientOptions, 'slackApiUrl'>;](https://github.com/slackapi/bolt-js/blob/b151b4c8ab3a422a7cfcf69fb655f2d61e857bcf/src/App.ts#L104)
3. Thus it should probably be easy to just add it in https://github.com/pablopaul/codeceptjs-slack-reporter/blob/c6e10684d802d65ed59901377e3a454643a9cb92/index.js#L27-L30 

As this would be a breaking change I suppose just using https://www.npmjs.com/package/patch-package is making more sense than actually changing this here, if my tests scheduled for later this month are successful adding an additional boolean `process.env.SLACK_API_FAILFAST` could result in a PR.
