### ISSUE TITLE
Error message is not shown in slack message - Still not resolved

### ISSUE THREAD

**Issue by exotlv** [pablopaul/codeceptjs-slack-reporter#4]
Hello,

Can you help with config error message. For now it's empty
![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/8436809/ac6d2771-ec22-48c8-8cb6-97ab100a10dd)

**Comment by kobenguyent** [comment]
Hey @exotlv did you see any error on console log when tests failed?

**Comment by exotlv** [comment]
@kobenguyent  I tried different ways:
![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/8436809/3a09bc59-d6e6-401d-acfd-bf87bebc9d74)
or
![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/8436809/c65a9849-47ba-44e2-9faa-bb78ea2ba807)

My actual runner: npx codeceptjs run-workers 6 --reporter mochawesome --reporter-options reportDir='./output',overwrite=false

Both cases I see {}

**Comment by pablopaul** [comment]
Please try a different reporter just to see if it works . Thanks.

Am Donnerstag, 17. August 2023 schrieb Exot ***@***.***>:

**Comment by exotlv** [comment]
@pablopaul 
My run w/o any reporter:
- npx codeceptjs run --steps
Same result
![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/8436809/7f885fb3-da39-46ae-93b7-b1666ec2a70c)

![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/8436809/aa28c18f-98e4-4a00-98ec-03dee6047d04)

**Comment by exotlv** [comment]
Also,
messageIntro is not taken from index.js
![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/8436809/d466ca48-9547-4222-8386-c96934814c1d)

**Comment by exotlv** [comment]
@pablopaul  @kobenguyent  any thoughts?

**Comment by exotlv** [comment]
Any way how to fix it?

**Comment by kobenguyent** [comment]
![Screenshot 2023-08-22 at 09 43 42](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/7845001/826f12f4-bc91-4b6b-86d4-0e6fd004ce7b)
it works for me.

**Comment by exotlv** [comment]
@kobenguyent 
very strange that I making changes in utilities.js but application still takes data from node_modules. Seems it's ignoring utilities.js from root. 
Maybe you could tell me where u put index.js and utilities.js ?

**Comment by kobenguyent** [comment]
are you modifying the index.js and utilities.js from `node_modules`? I'm just installing the package and use it
![Screenshot 2023-08-22 at 09 51 17](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/7845001/b97c3549-be69-4ad9-9a08-3f6c81fc78d7)

**Comment by exotlv** [comment]
What command you use to run test and reporter?

**Comment by kobenguyent** [comment]
````
  plugins: {
    allure: {
      enabled: true,
      require: '@codeceptjs/allure-legacy',
    },
    "slack-reporter": {
      require: "codeceptjs-slack-reporter",
      enabled: true
    }
  }
 ````
just like the instructions, enabled it and running it with codeceptjs commands.

**Comment by exotlv** [comment]
@kobenguyent 
still something is wrong: reasons are the same or even empty
![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/8436809/07e6c8b4-11e4-4666-a238-0b111a52839e)

**Comment by kobenguyent** [comment]
I could reproduce this bug when the browser is closed and made the test failed. ![image](https://github.com/pablopaul/codeceptjs-slack-reporter/assets/7845001/e0f810f2-d609-4c7d-a72d-5c438ad6f0be)

**Comment by exotlv** [comment]
@kobenguyent  you maybe know how to fix it?

**Comment by kobenguyent** [comment]
I'd think the fix shall be from CodeceptJS side as this slack reporter just receives the error from the test runner.

**Comment by exotlv** [comment]
By browser closed u mean: visible: false?

**Comment by kobenguyent** [comment]
I meant the browser is closed by the runner.

**Comment by exotlv** [comment]
@kobenguyent  any fixes from CodeceptJS what will resolve this issue?
